#!/usr/bin/env bash
#this script passes a file to a remote server
# -B sets batch mode
if [ "$#" -lt 4 ]; then
	printf "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY\n"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3"@"$2":~/
fi
