#!/usr/bin/env bash
# this script installs nginx, and installs a script with custom header
sudo apt-get update
sudo apt-get install -y nginx
sudo nginx start
sudo rm /etc/ngingx/nginx.conf
sudo wget https://raw.githubusercontent.com/Hillmonkey/holberton-system_engineering-devops/master/0x0F-load_balancer/nginx.conf
sudo cp nginx.conf /etc/nginx/nginx.conf
sudo rm nginx.conf
sudo service nginx restart
