#!/usr/bin/env bash
# this script kills apache2, sets nginx listen on 8080, runs nginx as non-root
pkill -u root apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 700 /etc/nginx/nginx.conf
sed -i 's/80 default_server/8080 default_server/' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
